### ISSUE TITLE
Error: 'DittoConfig' object has no attribute 'packing'

### ISSUE THREAD

**Issue by lucas-aixplain** [SALT-NLP/demonstrated-feedback#2]
Hello,
I followed the instructions in the README but am facing the following error when running `bash run.sh`:
```
[INFO|modeling_utils.py:4280] 2024-06-12 12:32:50,863 >> All model checkpoint weights were used when initializing MistralForCausalLM.

[INFO|modeling_utils.py:4288] 2024-06-12 12:32:50,863 >> All the weights of MistralForCausalLM were initialized from the model checkpoint at mistralai/Mistral-7B-Instruct-v0.2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use MistralForCausalLM for predictions without further training.
[INFO|configuration_utils.py:917] 2024-06-12 12:32:50,952 >> loading configuration file generation_config.json from cache at /home/jovyan/.cache/huggingface/hub/models--mistralai--Mistral-7B-Instruct-v0.2/snapshots/41b61a33a2483885c981aa79e0df6b32407ed873/generation_config.json
[INFO|configuration_utils.py:962] 2024-06-12 12:32:50,953 >> Generate config GenerationConfig {
  "bos_token_id": 1,
  "eos_token_id": 2
}

/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': dataset_text_field. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "/home/jovyan/demonstrated-feedback/scripts/run_ditto.py", line 430, in <module>
    main()
  File "/home/jovyan/demonstrated-feedback/scripts/run_ditto.py", line 356, in main
    trainer = FixedSFTTrainer(
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 191, in __init__
    if args.packing and data_collator is not None and isinstance(data_collator, DataCollatorForCompletionOnlyLM):
AttributeError: 'DittoConfig' object has no attribute 'packing'
[2024-06-12 12:32:52,339] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1562) of binary: /home/jovyan/my-conda-envs/ditto/bin/python
Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/ditto/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1088, in launch_command
    multi_gpu_launcher(args)
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/accelerate/commands/launch.py", line 733, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jovyan/my-conda-envs/ditto/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/run_ditto.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-12_12:32:52
  host      : jupyter-lucas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1562)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
## System info
Python 3.10.14
accelerate==0.31.0
peft==0.11.1
safetensors==0.4.3
torch==2.1.2
torchaudio==2.1.2
torchvision==0.16.2
transformers==4.41.2
trl==0.9.4

**Comment by oshaikh13** [comment]
Hm. It looks like the new version of trl deprecated some of the arguments to SFTTrainer.

Could you try switching back to trl==0.8.6? It should work then.

**Comment by wise-east** [comment]
I can verify that things work as expected with trl==0.8.6!

**Comment by oshaikh13** [comment]
Thanks a ton Justin!!

**Comment by lucas-aixplain** [comment]
Thank you very much @oshaikh13! It's working on my end as well.
